
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db.cc7psccjelfk.ap-northeast-2.rds.amazonaws.com:3306/emo_diary
    username: hdw9610
    password: ehddnr5103
#  h2:
#    console:
#      enable: true
#      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/dadaepodb
#    username: sa
#    password:

  resources:
    add-mappings: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#  sql:
#     init:
#      mode: always

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWRvbmd3b29rLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsCg==
  token-validity-in-seconds: 86400