
spring:

  h2:
    console:
      enable: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/dadaepodb
    username: sa
    password:

  #sql:
  #   init:
  #    mode: always

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWRvbmd3b29rLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsCg==
  token-validity-in-seconds: 86400