spring:
  h2:
    console:
      eanbled: true

    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb #jdbc:h2:/ddp
      username: sa
      password:

    sql:
      init:
        mode: always